# docker-compose.yml

version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    
    environment:
      - POSTGRES_USER=luciduser
      - POSTGRES_PASSWORD=postgres # Usando a senha simples que definimos
      - POSTGRES_DB=lucidcount_db
      # --- ALTERAÇÃO FINAL ---
      # Força o PostgreSQL a usar autenticação por senha md5, que é mais compatível
      - POSTGRES_HOST_AUTH_METHOD=md5
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    ports:
      - "5432:5432"
      
    restart: always

volumes:
  postgres_data:
    driver: local
